from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "src/research_memory/resources/taxonomy/schemas/v1"
PYTHON_OUTPUT = ROOT / "src/research_memory/generated/taxonomy_catalog.py"
PYTHON_INIT = ROOT / "src/research_memory/generated/__init__.py"
TYPESCRIPT_OUTPUT = ROOT / "desktop/src/generated/taxonomyCatalog.ts"


def _load(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _enum(schema: dict[str, object], property_name: str) -> list[str]:
    properties = schema["properties"]
    assert isinstance(properties, dict)
    value = properties[property_name]
    assert isinstance(value, dict)
    values = value["enum"]
    assert isinstance(values, list)
    return [str(item) for item in values]


def _contract_enums() -> dict[str, list[str]]:
    schema = _load(SCHEMAS / "contracts.schema.json")
    definitions = schema["$defs"]
    assert isinstance(definitions, dict)
    result: dict[str, list[str]] = {}
    for name, definition in definitions.items():
        assert isinstance(definition, dict)
        values = definition["enum"]
        assert isinstance(values, list)
        result[str(name)] = [str(item) for item in values]
    return result


def _literal(values: list[str]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def _typescript_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def render_python() -> str:
    node_schema = _load(SCHEMAS / "nodes.schema.json")
    edge_schema = _load(SCHEMAS / "edges.schema.json")
    pack_schema = _load(SCHEMAS / "packs.schema.json")
    state_schema = _load(SCHEMAS / "state_archetype.schema.json")
    state_properties = state_schema["properties"]
    assert isinstance(state_properties, dict)
    dimensions = state_properties["dimensions"]
    assert isinstance(dimensions, dict)
    items = dimensions["items"]
    assert isinstance(items, dict)
    dimension_properties = items["properties"]
    assert isinstance(dimension_properties, dict)
    value_type = dimension_properties["value_type"]
    assert isinstance(value_type, dict)
    node_items = node_schema["items"]
    assert isinstance(node_items, dict)
    enums = {
        "TaxonomyNodeType": _enum(node_items, "node_type"),
        "TaxonomyNodeStatus": _enum(node_items, "status"),
        "TaxonomyEdgeType": _enum(edge_schema["items"], "edge_type"),  # type: ignore[arg-type]
        "SpecialtyPackType": _enum(pack_schema["items"], "pack_type"),  # type: ignore[arg-type]
        "PackCurationStatus": _enum(pack_schema["items"], "curation_status"),  # type: ignore[arg-type]
        "StateValueType": [str(value) for value in value_type["enum"]],
        **_contract_enums(),
    }
    lines = [
        "# Generated by scripts/generate_taxonomy_types.py. Do not edit.",
        "from typing import Literal",
        "",
        "# fmt: off",
    ]
    lines.extend(f"{name} = {_literal(values)}" for name, values in enums.items())
    lines.extend(("# fmt: on", ""))
    return "\n".join(lines)


def render_typescript() -> str:
    node_schema = _load(SCHEMAS / "nodes.schema.json")
    edge_schema = _load(SCHEMAS / "edges.schema.json")
    pack_schema = _load(SCHEMAS / "packs.schema.json")
    state_schema = _load(SCHEMAS / "state_archetype.schema.json")
    state_properties = state_schema["properties"]
    assert isinstance(state_properties, dict)
    dimensions = state_properties["dimensions"]
    assert isinstance(dimensions, dict)
    items = dimensions["items"]
    assert isinstance(items, dict)
    dimension_properties = items["properties"]
    assert isinstance(dimension_properties, dict)
    value_type = dimension_properties["value_type"]
    assert isinstance(value_type, dict)
    node_items = node_schema["items"]
    assert isinstance(node_items, dict)
    enums = {
        "TaxonomyNodeType": _enum(node_items, "node_type"),
        "TaxonomyNodeStatus": _enum(node_items, "status"),
        "TaxonomyEdgeType": _enum(edge_schema["items"], "edge_type"),  # type: ignore[arg-type]
        "SpecialtyPackType": _enum(pack_schema["items"], "pack_type"),  # type: ignore[arg-type]
        "PackCurationStatus": _enum(pack_schema["items"], "curation_status"),  # type: ignore[arg-type]
        "StateValueType": [str(value) for value in value_type["enum"]],
        **_contract_enums(),
    }
    lines = [
        "// Generated by scripts/generate_taxonomy_types.py. Do not edit.",
        "",
    ]
    lines.extend(
        f"export type {name} = {_typescript_union(values)};" for name, values in enums.items()
    )
    lines.append("")
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = (
        (PYTHON_OUTPUT, render_python()),
        (
            PYTHON_INIT,
            '"""Generated cross-language contracts."""\n\n'
            "from research_memory.generated.taxonomy_catalog import *  # noqa: F403\n",
        ),
        (TYPESCRIPT_OUTPUT, render_typescript()),
    )
    return 0 if all(_write_or_check(path, value, args.check) for path, value in outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
